workspace:
  base: /go

pipeline:
  build:
    image: gobuffalo/buffalo:v0.11.0
    commands:
      - echo $GOROOT
      - echo $GOPATH
      - ls $GOPATH
      - pwd
      - printenv
      - go version
      - yarn install --no-progress
      - go get $(go list ./... | grep -v /vendor/)
      - buffalo test
      - buffalo build --static -o /bin/app
