workspace:
  base: /go

pipeline:
  build:
    image: gobuffalo/buffalo:v0.11.0  # golang:1.10
    commands:
      - echo $GOROOT
      - echo $GOPATH
      - ls $GOPATH
      - pwd
      - printenv
      - go version
      - go get $(go list ./... | grep -v /vendor/)
      - buffalo test
      - buffalo build --static -o /bin/app
